/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/myvetTheme.ts
 * Command: astryx theme build lib/myvetTheme.ts
 * Generated: 2026-07-25T17:24:47.299Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
