/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/myvetTheme.ts
 * Command: astryx theme build lib/myvetTheme.ts
 * Generated: 2026-07-25T17:24:47.300Z
 */

/// <reference path="./myvet.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const myvetTheme: DefinedTheme;
